services:
  - type: web
    name: ai-carbon-audit
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.enableCORS false
    plan: free
